# Generated by Django 6.0 on 2026-01-23 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0011_alter_adoptionrequest_id_alter_favorite_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostfoundreport',
            name='match_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lostfoundreport',
            name='match_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('not_matched', 'Not Matched')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='lostfoundreport',
            name='matched_report',
            field=models.ForeignKey(blank=True, help_text='Links a lost report to its corresponding found report (and vice versa).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_with', to='pets.lostfoundreport'),
        ),
    ]
