# Generated by Django 6.0 on 2026-01-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0012_lostfoundreport_match_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostfoundreport',
            name='match_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('reunited', 'Reunited'), ('not_matched', 'Not Matched')], default='pending', max_length=20),
        ),
    ]
